{ self, inputs, ... }:

{
  flake.nixosModules.secure-boot = { pkgs, lib, ... }:
  {
    boot.loader.systemd-boot.enable = lib.mkForce false;

    boot.lanzaboote = {
      enable = true;
      pkiBundle = "/var/lib/sbctl";
      autoGeneratedKeys.enable = true;
      autoEnrollKeys = {
        enable = true;
        includeMicrosoftKeys = true;
      };
    };

    boot.initrd.systemd.enable = true;
  };
}